# Generated by Django 3.2.2 on 2021-07-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_item_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('RED', 'red'), ('GREEN', 'green'), ('BLUE', 'blue'), ('WHITE', 'white'), ('BLACK', 'black')], default='RED', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
